# Generated by Django 4.1.3 on 2023-02-13 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='boardName',
            field=models.CharField(choices=[('Сделать', 'Todo'), ('В процессе', 'Inprogress'), ('Выполнено', 'Done')], default='Сделать', max_length=12),
        ),
    ]
