# Generated by Django 4.1.3 on 2023-02-13 13:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=300, verbose_name='Полное имя')),
                ('number', models.CharField(max_length=20, verbose_name='Номер')),
                ('product_url', models.URLField(default='https://default.com', max_length=20, verbose_name='Ссылка продукта')),
                ('product_amount', models.PositiveIntegerField(default=1, verbose_name='Количество продукта')),
                ('price', models.DecimalField(decimal_places=2, max_digits=19, verbose_name='Цена')),
                ('invoice', models.FileField(blank=True, null=True, upload_to='files', verbose_name='Счет')),
                ('address', models.CharField(blank=True, max_length=200, null=True, verbose_name='Адрес')),
                ('work', models.CharField(blank=True, max_length=200, null=True, verbose_name='Работа')),
                ('delivery_report', models.FileField(blank=True, null=True, upload_to='files', verbose_name='Aкт о доставке')),
                ('period', models.IntegerField(verbose_name='Период')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создано в')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обнавлено в')),
                ('order_code', models.CharField(blank=True, max_length=5, null=True, verbose_name='Код заказа')),
                ('passport_front', models.ImageField(blank=True, null=True, upload_to='images', verbose_name='Паспорт фронтальный')),
                ('passport_back', models.ImageField(blank=True, null=True, upload_to='images', verbose_name='Паспорт зад')),
                ('passport_number', models.CharField(blank=True, max_length=300, null=True, verbose_name='Номер паспорта')),
                ('passport_inn', models.CharField(blank=True, max_length=300, null=True, verbose_name='ИНН')),
                ('passport_issued_by', models.CharField(blank=True, max_length=300, null=True, verbose_name='Выдан')),
                ('passport_issued_date', models.DateField(blank=True, null=True, verbose_name='Дата выдачи')),
                ('created_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
            ],
        ),
    ]
